#!/usr/bin/env bash
# a script that ping the ip passed as an argument five times

ip_name=$1
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
else
    ping -c 5 "$ip_name"
fi